from pathlib import Path
p=Path('app/src/main/assets/index.html')
html=p.read_text(encoding='utf-8')
marker='function bindEvents(){'
if marker not in html: raise SystemExit('bindEvents marker missing')
js=r'''
function printReportFullV100(){
  const rows=currentReportRows||[]; if(!rows.length){toast('Yazdırılacak rapor verisi yok.');return;}
  const st=statsOf(rows), range=formatRange($('reportStart').value,$('reportEnd').value);
  const machines=enhancedGroupStats(rows,'machineId',state.machines), shifts=enhancedGroupStats(rows,'shiftId',state.shifts), masters=enhancedGroupStats(rows,'masterId',state.people).filter(x=>x.id!=='none');
  const scrapReasons=knownReasonStats(rows,'scrapReasonId',state.scrapReasons,'scrapQty','Nedeni belirtilmemiş'), downReasons=downtimeStatsCombined(rows), jobs=workOrderStats(rows), weeks=groupByPeriod(rows,'week');
  const groupTable=(title,data,capacity=false)=>`<section><h2>${title}</h2><table><thead><tr><th>Grup</th><th>Net</th><th>Brüt</th><th>İş</th><th>Kalıp</th><th>Fire</th><th>Fire %</th><th>Duruş</th><th>Duruş/İş</th><th>Net/İş</th><th>Tbk/Saat</th>${capacity?'<th>Kapasite %</th>':''}</tr></thead><tbody>${data.length?data.map(x=>`<tr><td>${esc(x.name)}</td><td>${fmtNum(x.good)}</td><td>${fmtNum(x.gross)}</td><td>${fmtNum(x.jobs)}</td><td>${fmtNum(x.plates)}</td><td>${fmtNum(x.scrap)}</td><td>${fmtPct(x.rate)}</td><td>${fmtNum(x.down)} dk</td><td>${fmtNum(Math.round(x.downPerJob))} dk</td><td>${fmtNum(Math.round(x.avgJob))}</td><td>${x.hourly?fmtNum(Math.round(x.hourly)):'-'}</td>${capacity?`<td>${x.capacityUse==null?'Tanımsız':fmtPct(x.capacityUse)}</td>`:''}</tr>`).join(''):'<tr><td colspan="12">Veri yok</td></tr>'}</tbody></table></section>`;
  const pareto=(title,data,unit)=>`<section><h2>${title}</h2><table><thead><tr><th>Neden</th><th>Değer</th><th>Pay</th></tr></thead><tbody>${data.length?data.slice(0,15).map(x=>`<tr><td>${esc(x.name)}</td><td>${fmtNum(x.value)} ${unit}</td><td>${fmtPct(x.value*100/(data.reduce((a,b)=>a+b.value,0)||1))}</td></tr>`).join(''):'<tr><td colspan="3">Veri yok</td></tr>'}</tbody></table></section>`;
  const topFire=[...jobs].sort((a,b)=>b.rate-a.rate).slice(0,12), topDown=[...jobs].sort((a,b)=>b.down-a.down).slice(0,12);
  const jobTable=(title,data)=>`<section><h2>${title}</h2><table><thead><tr><th>İş Emri</th><th>Makine</th><th>Vardiya</th><th>Usta</th><th>Net</th><th>Fire</th><th>Fire %</th><th>Duruş</th><th>Kalıp</th><th>Tbk/Saat</th><th>Renk</th><th>Lak/UV</th></tr></thead><tbody>${data.length?data.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.machines.join(', ')||'-')}</td><td>${esc(x.shifts.join(', ')||'-')}</td><td>${esc(x.masters.join(', ')||'-')}</td><td>${fmtNum(x.good)}</td><td>${fmtNum(x.scrap)}</td><td>${fmtPct(x.rate)}</td><td>${fmtNum(x.down)} dk</td><td>${fmtNum(x.plates)}</td><td>${x.hourly?fmtNum(Math.round(x.hourly)):'-'}</td><td>${esc(x.colors.join(', ')||'-')}</td><td>${esc(x.coating)}</td></tr>`).join(''):'<tr><td colspan="12">Veri yok</td></tr>'}</tbody></table></section>`;
  const colorMap=new Map(); rows.forEach(r=>{const k=r.colors!=null&&Number(r.colors)>0?String(Number(r.colors)):'Belirtilmemiş';if(!colorMap.has(k))colorMap.set(k,[]);colorMap.get(k).push(r)});
  const colors=[...colorMap.entries()].map(([name,rr])=>{const s=statsOf(rr);return{name:name==='Belirtilmemiş'?name:name+' renk',...s}}).sort((a,b)=>b.good-a.good);
  const coatings=[['UV Laklı',rows.filter(r=>r.uvLak===true)],['Laklı',rows.filter(r=>r.lak===true)],['Lak / UV Yok',rows.filter(r=>r.lak===false&&r.uvLak===false)],['Belirtilmemiş',rows.filter(r=>r.lak==null||r.uvLak==null)]].map(([name,rr])=>{const s=statsOf(rr);return{name,...s}});
  const simpleMix=(title,data)=>`<section><h2>${title}</h2><table><thead><tr><th>Tip</th><th>İş</th><th>Net</th><th>Fire</th><th>Fire %</th><th>Duruş</th><th>Kalıp</th></tr></thead><tbody>${data.map(x=>`<tr><td>${esc(x.name)}</td><td>${fmtNum(x.jobs)}</td><td>${fmtNum(x.good)}</td><td>${fmtNum(x.scrap)}</td><td>${fmtPct(x.rate)}</td><td>${fmtNum(x.down)} dk</td><td>${fmtNum(x.plates)}</td></tr>`).join('')}</tbody></table></section>`;
  const weekly=`<section><h2>Haftalık Trend</h2><table><thead><tr><th>Dönem</th><th>Net</th><th>Fire</th><th>Fire %</th><th>Duruş</th><th>İş</th><th>Kalıp</th></tr></thead><tbody>${weeks.length?weeks.map(x=>`<tr><td>${esc(x.label)}</td><td>${fmtNum(x.good)}</td><td>${fmtNum(x.scrap)}</td><td>${fmtPct(x.rate)}</td><td>${fmtNum(x.down)} dk</td><td>${fmtNum(x.jobs)}</td><td>${fmtNum(x.plates)}</td></tr>`).join(''):'<tr><td colspan="7">Veri yok</td></tr>'}</tbody></table></section>`;
  const [ps,pe]=($('reportStart').value&&$('reportEnd').value)?previousPeriodRange($('reportStart').value,$('reportEnd').value):['',''], prev=ps?statsOf(filterReportRows(ps,pe)):null;
  const comparison=prev?`<section><h2>Önceki Dönem Karşılaştırması</h2><p class="note">${esc(formatRange(ps,pe))}</p><table><thead><tr><th>Gösterge</th><th>Bu Dönem</th><th>Önceki</th><th>Değişim</th></tr></thead><tbody><tr><td>Net Baskı</td><td>${fmtNum(st.good)}</td><td>${fmtNum(prev.good)}</td><td>${deltaText(pctChange(st.good,prev.good),'%')}</td></tr><tr><td>Fire Oranı</td><td>${fmtPct(st.rate)}</td><td>${fmtPct(prev.rate)}</td><td>${deltaText(st.rate-prev.rate,' puan')}</td></tr><tr><td>Duruş</td><td>${fmtNum(st.down)} dk</td><td>${fmtNum(prev.down)} dk</td><td>${deltaText(pctChange(st.down,prev.down),'%')}</td></tr><tr><td>İş Sayısı</td><td>${fmtNum(st.jobs)}</td><td>${fmtNum(prev.jobs)}</td><td>${deltaText(pctChange(st.jobs,prev.jobs),'%')}</td></tr><tr><td>Kalıp</td><td>${fmtNum(st.plates)}</td><td>${fmtNum(prev.plates)}</td><td>${deltaText(pctChange(st.plates,prev.plates),'%')}</td></tr></tbody></table></section>`:'';
  const detail=rows.slice().sort((a,b)=>`${a.date}|${a.workOrder}`.localeCompare(`${b.date}|${b.workOrder}`)).map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(getById(state.shifts,r.shiftId)?.name||'-')}</td><td>${esc(getById(state.machines,r.machineId)?.name||'-')}</td><td>${esc(getById(state.people,r.masterId)?.name||'-')}</td><td>${esc(r.workOrder||'-')}</td><td>${fmtNum(r.goodQty)}</td><td>${fmtNum(r.plateQty)}</td><td>${fmtNum(r.scrapQty)}</td><td>${fmtPct(scrapRate(r))}</td><td>${fmtNum(r.downtimeMin)} dk</td><td>${r.colors??'-'}</td><td>${r.uvLak===true?'UV':r.lak===true?'Lak':r.lak===false&&r.uvLak===false?'Yok':'-'}</td></tr>`).join('');
  const doc=`<!doctype html><html><head><meta charset="utf-8"><title>Üretim Performans Raporu</title><style>@page{size:A4 landscape;margin:9mm}body{font-family:Arial,sans-serif;color:#15171a;font-size:10px}h1{font-size:22px;margin:0 0 3px}h2{font-size:14px;margin:0 0 8px}.note{color:#66717e}.cover{border-bottom:2px solid #222;padding-bottom:12px;margin-bottom:14px}.kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:7px;margin:12px 0}.kpi{border:1px solid #d5d9de;padding:9px;border-radius:5px}.kpi small{display:block;color:#707985}.kpi b{display:block;font-size:15px;margin-top:4px}section{margin:15px 0;break-inside:avoid}table{width:100%;border-collapse:collapse;font-size:8.7px}th,td{border-bottom:1px solid #dfe2e6;padding:5px;text-align:right;vertical-align:top}th{background:#f0f2f4}th:first-child,td:first-child{text-align:left}.page{break-before:page}.muted{color:#6f7884}</style></head><body><div class="cover"><h1>Üretim Performans Merkezi — Yönetici Raporu</h1><div class="note">${esc(range)} • ${fmtNum(rows.length)} üretim kaydı</div></div><div class="kpis"><div class="kpi"><small>Net Baskı</small><b>${fmtNum(st.good)}</b></div><div class="kpi"><small>Brüt Baskı</small><b>${fmtNum(st.good+st.scrap)}</b></div><div class="kpi"><small>Fire</small><b>${fmtNum(st.scrap)} / ${fmtPct(st.rate)}</b></div><div class="kpi"><small>Duruş</small><b>${fmtNum(st.down)} dk</b></div><div class="kpi"><small>İş</small><b>${fmtNum(st.jobs)}</b></div><div class="kpi"><small>Kalıp</small><b>${fmtNum(st.plates)}</b></div></div>${comparison}${groupTable('Makine Performansı',machines,true)}${groupTable('Vardiya Performansı',shifts)}${groupTable('Usta Performansı',masters)}<div class="page"></div>${pareto('Fire Pareto',scrapReasons,'adet')}${pareto('Duruş Pareto',downReasons,'dk')}${jobTable('En Yüksek Fire Oranlı İşler',topFire)}${jobTable('En Yüksek Duruşlu İşler',topDown)}${simpleMix('Renk Sayısına Göre İş Karması',colors)}${simpleMix('Lak / UV Dağılımı',coatings)}${weekly}<div class="page"></div><section><h2>Detaylı Üretim Kayıtları</h2><table><thead><tr><th>Tarih</th><th>Vardiya</th><th>Makine</th><th>Usta</th><th>İş Emri</th><th>Net</th><th>Kalıp</th><th>Fire</th><th>Fire %</th><th>Duruş</th><th>Renk</th><th>Lak/UV</th></tr></thead><tbody>${detail}</tbody></table></section></body></html>`;
  if(isAndroidNative()&&typeof window.AndroidApp.printHtml==='function'){window.AndroidApp.printHtml('Uretim Performans Raporu',doc);return;}
  const w=window.open('','_blank'); if(!w){toast('Yazdırma penceresi engellendi.');return;} w.document.write(doc.replace('</body>','<script>window.onload=()=>setTimeout(()=>window.print(),150)<\\/script></body>'));w.document.close();
}
'''
html=html.replace(marker,js+'\n'+marker,1)
changed=False
for old in ["if($('printReportBtn'))$('printReportBtn').onclick=printMainReport;","if($('printReportBtn')) $('printReportBtn').onclick=printMainReport;"]:
    if old in html:
        html=html.replace(old,old.replace('printMainReport','printReportFullV100'),1);changed=True;break
if not changed: raise SystemExit('print button binding missing')
p.write_text(html,encoding='utf-8')
print('patched-full-pdf',len(html))