from pathlib import Path
p=Path('app/src/main/java/com/tufanprintops/uretimperformans/MainActivity.java')
s=p.read_text(encoding='utf-8')
old='''        @JavascriptInterface\n        public void printHtml(String title, String html) {\n            runOnUiThread(() -> {\n                printWebView = new WebView(MainActivity.this);\n                printWebView.getSettings().setJavaScriptEnabled(false);\n                printWebView.setWebViewClient(new WebViewClient() {\n                    @Override public void onPageFinished(WebView view, String url) {\n                        PrintManager pm = (PrintManager) getSystemService(Context.PRINT_SERVICE);\n                        String job = (title == null || title.trim().isEmpty()) ? "Üretim Raporu" : title;\n                        pm.print(job, view.createPrintDocumentAdapter(job), null);\n                    }\n                });\n                printWebView.loadDataWithBaseURL("https://print.local/", html, "text/html", "UTF-8", null);\n            });\n        }\n'''
new='''        @JavascriptInterface\n        public void printHtml(String title, String html) {\n            runOnUiThread(() -> {\n                try {\n                    if (printWebView != null) {\n                        try { printWebView.stopLoading(); printWebView.destroy(); } catch (Exception ignored) {}\n                        printWebView = null;\n                    }\n                    final WebView pv = new WebView(MainActivity.this);\n                    printWebView = pv;\n                    WebSettings ps = pv.getSettings();\n                    ps.setJavaScriptEnabled(false);\n                    ps.setDomStorageEnabled(false);\n                    ps.setLoadWithOverviewMode(true);\n                    ps.setUseWideViewPort(true);\n                    pv.setWebViewClient(new WebViewClient() {\n                        private boolean printRequested = false;\n                        @Override public void onPageFinished(WebView view, String url) {\n                            if (printRequested || printWebView != view) return;\n                            printRequested = true;\n                            view.postDelayed(() -> {\n                                try {\n                                    PrintManager pm = (PrintManager) getSystemService(Context.PRINT_SERVICE);\n                                    if (pm == null) throw new IllegalStateException("Android yazdırma servisi bulunamadı");\n                                    String job = (title == null || title.trim().isEmpty()) ? "Üretim Raporu" : title.trim();\n                                    pm.print(job, view.createPrintDocumentAdapter(job), null);\n                                    if (webView != null) webView.post(() -> webView.evaluateJavascript("if(window.nativePrintStarted){nativePrintStarted();}", null));\n                                } catch (Exception ex) {\n                                    final String msg = ex.getMessage() == null ? ex.toString() : ex.getMessage();\n                                    if (webView != null) webView.post(() -> webView.evaluateJavascript("if(window.nativePrintFailed){nativePrintFailed(" + jsQuote(msg) + ");}", null));\n                                }\n                            }, 450);\n                        }\n                    });\n                    String safeHtml = (html == null || html.trim().isEmpty()) ? "<html><body><h2>Rapor içeriği boş.</h2></body></html>" : html;\n                    pv.loadDataWithBaseURL("https://print.local/", safeHtml, "text/html", "UTF-8", null);\n                } catch (Exception ex) {\n                    final String msg = ex.getMessage() == null ? ex.toString() : ex.getMessage();\n                    if (webView != null) webView.post(() -> webView.evaluateJavascript("if(window.nativePrintFailed){nativePrintFailed(" + jsQuote(msg) + ");}", null));\n                }\n            });\n        }\n'''
if old not in s: raise SystemExit('printHtml block not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('patched-main-v150')
